---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
webhooks:
  - name: {{ .Values.name }}-svc.{{ .Values.namespace }}.svc
    clientConfig:
      service:
        name: {{ .Values.name }}-svc
        namespace: {{ .Values.namespace }}
        path: "/"
      caBundle: {{ .Values.caBundle }}
    rules:  
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
